Pages/Admin.cshtml.cs
using Blog.Interfaces;
using Blog.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Blog.Pages
{
    public class AdminModel : PageModel
    {
        public UserVM UserVM { get; set; }
        public string StatusMessage { get; set; }

        [BindProperty]
        public List<UserVM> UsersVM { get; set; }

        private IUserService _userService;

        private readonly UserManager<IdentityUser> _manager;

        public AdminModel(IUserService userService, UserManager<IdentityUser> manager)
        {
            _userService = userService;
            _manager = manager;
        }
        public void OnGet()
        {
            UsersVM = _userService.GetUsers("");
        }

        public IActionResult OnPost(string delete_username)
        {
            System.Diagnostics.Debug.WriteLine("PPPPPPPPPPPP"+delete_username+"PPPPPPPPPPPPPPPPp");
            IdentityUser user = _userService.GetDeleteUser(delete_username);
            _userService.DeleteUser(user);
            StatusMessage = "User successfully destroyed";
            //UsersVM = _userService.GetUsers("");
            return Page();
        }
    }
}

Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace Blog.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Pages/Index.cshtml.cs
using Blog.Data;
using Blog.Interfaces;
using Blog.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Runtime.CompilerServices;
using System.Security.Claims;
using System.Text.Json;
using System.Text.RegularExpressions;

namespace Blog.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        private readonly IPostService _postService;
        private readonly IUserService _userservice;

        [BindProperty]
        public IFormFile? Image { get; set; }

        [BindProperty]
        public Post Post { get; set; }

        [BindProperty]
        public Comment Comment { get; set; }

        public PaginatedList<Post> Posts { get; set; }

        public List<Comment> Comments { get; set; }


        public IndexModel(ILogger<IndexModel> logger, IPostService service, IUserService userService)
        {
            _logger = logger;
            _postService = service;
            _userservice = userService;
        }

        public void OnGet(int pageIndex = 1)
        {
            Posts = _postService.GetPosts(pageIndex);
            Comments = _postService.GetComments();
        }

        public IActionResult OnPost(int pageIndex = 1)
        {

            Post.Author = User.FindFirstValue(ClaimTypes.NameIdentifier);
            _postService.AddPost(Post, Image);
            Posts = _postService.GetPosts(pageIndex);
            return RedirectToPage();
        }

        public IActionResult OnPostComment(int Postid, int pageIndex = 1)
        {
            Comment.UserID = User.FindFirstValue(ClaimTypes.NameIdentifier);
            Comment.AddressIP = HttpContext.Connection.RemoteIpAddress?.ToString();
            _postService.AddComment(Comment, Postid);
            Posts = _postService.GetPosts(pageIndex);
            return RedirectToPage();
        }

        public IActionResult OnPostDeleteComment(int comid, int pageIndex = 1)
        {
            _postService.DeleteComment(comid);
            Posts = _postService.GetPosts(pageIndex);
            return RedirectToPage();
        }
    }
}

Pages/ManagePosts.cshtml.cs
using Blog.Interfaces;
using Blog.Models;
using Blog.Services;
using Blog.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Security.Claims;

namespace Blog.Pages
{
    public class ManagePostsModel : PageModel
    {
        [BindProperty]
        public IFormFile Image { get; set; }

        [BindProperty]
        public Post Post { get; set; }

        [BindProperty]
        public List<Post> Posts { get; set; }

        private IPostService _postService;
        private IUserService _userService;

        public ManagePostsModel(IPostService postService, IUserService userService)
        {
            _postService = postService;
            _userService = userService;
        }

        public void OnGet()
        {
            var userid = User.FindFirstValue(ClaimTypes.NameIdentifier);
            Posts = _postService.getUsersPosts(userid);
        }

        public void OnPostDelete(int delete_post) 
        {
            _postService.DeletePost(delete_post);
            Posts = _postService.getUsersPosts(User.FindFirstValue(ClaimTypes.NameIdentifier));

        }

        public void OnPostEdit(string text, int edit_post)
        {
            System.Diagnostics.Debug.WriteLine(edit_post);
            System.Diagnostics.Debug.WriteLine(Request.Form["text"]);
            Post.Description = Request.Form["text"];
            _postService.EditPost(edit_post, Post, Image);
            Posts = _postService.getUsersPosts(User.FindFirstValue(ClaimTypes.NameIdentifier));

        }
    }
}

Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Blog.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Pages/UserProfile.cshtml.cs
using Blog.Data;
using Blog.Interfaces;
using Blog.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Security.Claims;

namespace Blog.Pages
{
    public class UserProfileModel : PageModel
    {
        public PaginatedList<Post> Posts { get; set; }
        public List<Comment> Comments { get; set; }

        [BindProperty]
        public Comment Comment { get; set; }

        [BindProperty(SupportsGet = true)]
        public string UserId { get; set; }

        public IPostService _postService { get; set; }
        public IUserService _userService { get; set; }

        public UserProfileModel(IPostService postService, IUserService userService)
        {
            _postService = postService;
            _userService = userService;
        }
        public void OnGet(int pageIndex = 1)
        {
            Posts = _postService.GetUserPaginatedPosts(UserId);
            Comments = _postService.GetComments();
        }
        public IActionResult OnPostComment(int Postid, int pageIndex = 1)
        {

            Comment.UserID = User.FindFirstValue(ClaimTypes.NameIdentifier);
            Comment.AddressIP = HttpContext.Connection.RemoteIpAddress?.ToString();
            _postService.AddComment(Comment, Postid);
            Posts = _postService.GetPosts(pageIndex);
            Comments = _postService.GetComments();
            return Page();
        }

        public IActionResult OnPostDeleteComment(int comid, int pageIndex = 1)
        {
            _postService.DeleteComment(comid);
            Posts = _postService.GetPosts(pageIndex);
            Comments = _postService.GetComments();
            return Page();
        }
    }
}

Pages/Admin.cshtml
@page
@model Blog.Pages.AdminModel
@{
}

<h1>Admin Tools</h1>

<div class="alert alert-success" role="alert">@Model.StatusMessage</div>

<table class="table">
    <tr>
        <th>Username</th>
        <th>Email</th>
        <th></th>
    </tr>
    @foreach (var item in Model.UsersVM)
    {
        <tr>
            <td>@item.Username</td>
            <td>@item.Email</td>
            <td>
                <form method="post">
                    <input type="hidden" name="delete_username" value="@item.Username" />
                    <button type="submit" id="btn" class="btn btn-primary">Delete</button>
                </form>
            </td>
        </tr>
    }
</table>

Pages/Index.cshtml
@page
@using Blog.Models;
@using Blog.Interfaces;
@inject IUserService _userservice;
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Blog</h1>
</div>

@if (User.Identity.IsAuthenticated)
{
    <div class="text-center">
        <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#CreatePostModal">
            Add post
        </button>
    </div>
}



<!-- Modal -->
<div class="modal fade" id="CreatePostModal" tabindex="-1" role="dialog" aria-labelledby="modal-title" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modal-title">Create new Roast</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
                </button>
            </div>
            <div class="modal-body">
                <form method="post" enctype="multipart/form-data">
                    <div class="form-group">
                        <label asp-for="Post.Title" class="col-form-label"></label>
                        <input asp-for="Post.Title" type="text" class="form-control" id="PostTitle" placeholder="Title" />
                        <label asp-for="Post.Description" class="form-label">Post Title</label>
                        <textarea asp-for="Post.Description" type="text" class="form-control" id="PostText" placeholder="Whats new"></textarea>
                        <label asp-for="Image" class="col-form-label"></label>
                        <input asp-for="Image" type="file" class="form-control" id="PostImage"/>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary">Post</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>



<div id="posts">
    @if (Model.Posts.Posts.Count() != 0)
    {

        foreach(Post post in Model.Posts.Posts)
        {
            <div class="post rounded">
                <div id="header" class="header">
                    <a class="Author" href="/UserProfile/?UserId=@post.Author">
                        @_userservice.GetUserName(post.Author)
                    </a>
                    <div class="title">
                        @post.Title
                    </div>
                    <div class="date">@post.date</div>
                </div>
                <div class="postbody">
                    <div class="img">
                        @if (post.SerializedImages != "")
                        {
                            <img src="data:image/jpg;base64,@post.SerializedImages" width="480px" height="480px" />
                        }
                    </div>
                    <div id="posttext" class="text">
                        @post.Description
                    </div>
                </div>
                
                <div class="commentsection">
                    @if (post.Commends != "&")
                    {
                        foreach (Comment com in Model.Comments)
                        {
                            var username = _userservice.GetUserName(com.UserID);
                            if (post.Commends.Contains("&" + com.Id.ToString() + "&"))
                            {
                                <div class="comment">
                                    <div class="commentauthor">
                                        @username
                                    </div>
                                    <div class="commentbody">
                                        <div class="commenttext">@com.Text</div>
                                        
                                    </div>
                                    @if (username == User.Identity.Name || User.IsInRole("admin"))
                                    {
                                        <form method="post" asp-page-handler="DeleteComment">
                                            <button type="submit" class="delbutton btn btn-primary" name="comID" value="@com.Id">Del</button>
                                        </form>
                                    }
                                </div>
                            }
                        }
                    }
                </div>
                
                @if(User.Identity.IsAuthenticated)
                {
                    <form method="post" asp-page-handler="Comment" class="form-inline">
                        <div class="form-group mb-2">
                            <label asp-for="Comment.Text" class="col-form-label" hidden></label>
                            <input asp-for="Comment.Text" type="text" class="form-control" id="PostTitle" placeholder="Got something to add?" />
                            <button type="submit" class="btn btn-primary" name="Postid" value="@post.Id" hidden>Post</button>
                        </div>
                    </form>
                }
            </div>


        }
    }
</div>

<nav class="justify-content-center">
    <ul class="pagination">
        <li class="page-item @(Model.Posts.HasPreviousPage ? "" : "disabled")">
            <a class="page-link" asp-page="./Index" asp-route-pageIndex=@(Model.Posts.PageIndex - 1)>Previous</a>
        </li>
        @for (int i = 1; i <= Model.Posts.TotalPages; i++)
        {
            <li class="page-item @(i == Model.Posts.PageIndex ? "active" : "")">
                <a class="page-link" asp-page="./Index" asp-route-pageIndex=@i>@i</a>
            </li>
        }
        <li class="page-item @(Model.Posts.HasNextPage ? "" : "disabled")">
            <a class="page-link" asp-page="./Index" asp-route-pageIndex=@(Model.Posts.PageIndex + 1)>Next</a>
        </li>
    </ul>
</nav>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Pages/ManagePosts.cshtml
@page
@model Blog.Pages.ManagePostsModel
@{
}

<h1>Admin Tools</h1>

@*<div class="alert alert-success" role="alert">@Model.StatusMessage</div>*@

<table class="table">
    <tr>
        <th>Title</th>
        <th>Date</th>
        <th></th>
        <th></th>
    </tr>
    @foreach (var item in Model.Posts)
    {
        <tr>
            <td>@item.Title</td>
            <td>@item.date</td>
            <td>
@*                <form method="post" asp-page-handler="Edit">
                    <input type="hidden" name="modify_post" value="@item.Id" />
                    <button type="submit" id="btn" class="btn btn-primary">Edit</button>
                </form>*@
                <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#EditPostModal-@item.Id">
                    Edit
                </button>
            </td>
            <td>
                <form method="post" asp-page-handler="Delete">
                    <input type="hidden" name="delete_post" value="@item.Id" />
                    <button type="submit" id="btn" class="btn btn-primary">Delete</button>
                </form>
            </td>
        </tr>

        <!-- Modal -->
        <div class="modal fade" id="EditPostModal-@item.Id" tabindex="-1" role="dialog" aria-labelledby="modal-title" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="modal-title">Create new Roast</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
                            @*<span aria-hidden="true">&times;</span>*@
                        </button>
                    </div>
                    <div class="modal-body">
                        <form method="post" enctype="multipart/form-data" asp-page-handler="Edit">
                            <div class="form-group">
                                <label asp-for="Post.Title" class="col-form-label"></label>
                                <input asp-for="Post.Title" type="text" class="form-control" id="PostTitle" placeholder="Title" value="@item.Title"/>
                                <label asp-for="Post.Description" class="form-label"></label>
                                <textarea type="text" id="text" name="text" class="form-control">@item.Description</textarea>
                                <label asp-for="Image" class="col-form-label"></label>
                                <input asp-for="Image" type="file" class="form-control" id="PostImage" />
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                <button type="submit" class="btn btn-primary" name="edit_post" value="@item.Id">Post</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    }
</table>

Pages/UserProfile.cshtml
@page
@using Blog.Interfaces;
@using Blog.Models;
@inject IUserService _userservice;
@model Blog.Pages.UserProfileModel
@{
}

<h1 class="text-center">@_userservice.GetUserName(Model.UserId)'s Posts</h1>

<div id="posts">
    @if (Model.Posts.Posts.Count() != 0)
    {
        foreach (Post post in Model.Posts.Posts)
        {
            <div class="post rounded" role="button" data-bs-toggle="modal" data-bs-target="#InspectPostModal">
                <div id="header" class="header">
                    <a class="Author" href="/UserProfile/?UserId=@post.Author">
                        @_userservice.GetUserName(post.Author)
                    </a>
                    <div class="title">
                        @post.Title
                    </div>
                    <div class="date">@post.date</div>
                </div>
                <div class="postbody">
                    <div class="img">
                        @if (post.SerializedImages != "")
                        {
                            <img src="data:image/jpg;base64,@post.SerializedImages" width="480px" height="480px" />
                        }
                    </div>
                    <div class="text">
                        @post.Description
                    </div>
                </div>
                <div class="commentsection">
                    @if (post.Commends != "&")
                    {
                        foreach (Comment com in Model.Comments)
                        {
                            var username = _userservice.GetUserName(com.UserID);
                            if (post.Commends.Contains("&" + com.Id.ToString() + "&"))
                            {
                                <div class="comment">
                                    <div class="commentauthor">
                                        @username
                                    </div>
                                    <div class="commentbody">
                                        <div class="commenttext">@com.Text</div>

                                    </div>
                                    @if (username == User.Identity.Name || User.IsInRole("admin"))
                                    {
                                        <form method="post" asp-page-handler="DeleteComment">
                                            <input type="hidden" asp-for="@Model.UserId"/>
                                            <button type="submit" class="delbutton btn btn-primary" name="comID" value="@com.Id">Del</button>
                                        </form>
                                    }
                                </div>
                            }
                        }
                    }
                </div>
                @if (User.Identity.IsAuthenticated)
                {
                    <form method="post" asp-page-handler="Comment" class="form-inline">
                        <div class="form-group mb-2">
                            <label asp-for="Comment.Text" class="col-form-label" hidden></label>
                            <input asp-for="Comment.Text" type="text" class="form-control" id="PostTitle" placeholder="Got something to add?" />
                            <input type="hidden" asp-for="@Model.UserId" />
                            <button type="submit" class="btn btn-primary" name="Postid" value="@post.Id" hidden>Post</button>
                        </div>
                    </form>
                }
            </div>
        }
    }
</div>